# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jemoji


# SCSS
sass:
  style: :compressed

# Permalinks
permalink: pretty

jekyll-mentions: https://twitter.com

# Site info
url: "http://darn.es"
title: "David Darnes"
name: "David Darnes"
description: "Web Designer & Front-end Developer"
logo: "https://avatars1.githubusercontent.com/u/1177460?s=300"

twitter:
  username: daviddarnes

author:
  twitter: daviddarnes
